SERVICE_OSM_TAGS = {
    "school":                   [("amenity", "school")],
    "kindergarten":             [("amenity", "kindergarten")],
    "hospital":                 [("amenity", "hospital")],
    "polyclinic":               [("amenity", "clinic"), ("amenity", "doctors")],
    "pitch":                    [("leisure", "pitch")],
    "swimming_pool":            [("leisure", "swimming_pool")],
    "stadium":                  [("leisure", "stadium"), ("leisure", "ice_rink")],
    "theatre":                  [("amenity", "theatre")],
    "museum":                   [("tourism", "museum")],
    "cinema":                   [("amenity", "cinema")],
    "mall":                     [("shop", "mall"), ("shop", "shopping_centre")],
    "convenience":              [("shop", "convenience")],
    "supermarket":              [("shop", "supermarket")],
    "cemetery":                 [("amenity", "grave_yard"), ("landuse", "cemetery")],
    "religion":                 [("amenity", "place_of_worship")],
    "market":                   [("amenity", "marketplace")],
    "university":               [("amenity", "university")],
    "playground":               [("leisure", "playground")],
    "pharmacy":                 [("amenity", "pharmacy")],
    "fuel":                     [("amenity", "fuel")],
    "beach":                    [("natural", "beach"), ("natural", "coastline"), ("leisure", "beach_resort")],
    "train_building":           [("building", "train_station"), ("public_transport", "station")],
    "bank":                     [("amenity", "bank")],
    "lawyer":                   [("office", "lawyer")],
    "cafe":                     [("amenity", "cafe")],
    # "subway_entrance":          [("railway", "subway_entrance")],
    # "multifunctional_center":   [("government", "public_service")],
    "hairdresser":              [("shop", "hairdresser")],
    "restaurant":               [("amenity", "restaurant")],
    "bar":                      [("amenity", "bar"), ("amenity", "pub")],
    "park":                     [("leisure", "park"), ("leisure", "garden")],
    "government":               [("government", "ministry"), ("government", "administrative")],
    # "recruitment":              [("office", "employment_agency")],
    "hotel":                    [("tourism", "hotel")],
    # "zoo":                      [("tourism", "zoo")],
    "post":                     [("amenity", "post_office")],
    "police":                   [("amenity", "police")],
    "dog_park":                 [("leisure", "dog_park")],
    "hostel":                   [("tourism", "hostel")],
    "bakery":                   [("shop", "bakery")],
    "parking":                  [("amenity", "parking")],
    # "guest_house":              [("tourism", "guest_house")],
    # "reserve":                  [("leisure", "nature_reserve")],
    # "sanatorium":               [("amenity", "sanatorium")],
    "embankment":               [("man_made", "embankment")],
    # "machine_building_plant":   [("product", "machinery")],
    "brewery":                  [("craft", "brewery")],
    # "oil_refinery":             [("industrial", "refinery")],
    "plant_of_building_materials":[("building", "industrial")],
    # "wastewater_plant":         [("man_made", "wastewater_plant")],
    # "water_works":              [("man_made", "water_works")],
    "substation":               [("power", "substation")],
    "train_station":            [("railway", "station")],
    # "bus_station":              [("amenity", "bus_station")],
    # "bus_stop":                 [("highway", "bus_stop"), ("railway", "tram_stop")],
    "pier":                     [("man_made", "pier")],
    # "animal_shelter":           [("amenity", "animal_shelter")],
    # "prison":                   [("amenity", "prison")],
    "landfill":                 [("landuse", "landfill")],
    # "plant_nursery":            [("landuse", "plant_nursery")],
    "greenhouse_complex":       [("building", "greenhouse")],
    "warehouse":                [("building", "warehouse")],
    # "farmland":                 [("landuse", "farmland")],
    # "livestock":                [("building", "livestock")],
    # "nursing_home":             [("amenity", "nursing_home"), ("social_facility", "group_home")],
    "library":                  [("amenity", "library")],
    # "gallery":                  [("tourism", "gallery")],
    # "monastery":                [("amenity", "monastery")],
    # "diplomatic":               [("office", "diplomatic")],
    "court_house":              [("amenity", "courthouse")],
    "veterinary":               [("amenity", "veterinary")],
    "notary":                   [("lawyer", "notary")],
    "houseware":                [("shop", "houseware"), ("shop", "chemist"), ("shop", "hardware")],
    "car_wash":                 [("amenity", "car_wash")],
    # "golf_course":              [("leisure", "golf_course")],
    # "plant_gas_oil":            [("power", "plant")],
    # "railway_roundhouse":       [("railway", "roundhouse")],
    # "aeroway_terminal":         [("aeroway", "terminal")],
    # "crematorium":              [("amenity", "crematorium")],
}


SERVICE_CAPACITY_RANGE = {
    "school":                   (500, 1000),
    "kindergarten":             (100, 500),
    "hospital":                 (100, 500),
    "polyclinic":               (10, 200),
    "swimming_pool":            (100, 200),
    "stadium":                  (100, 500),
    "theatre":                  (500, 1000),
    "museum":                   (100, 500),
    "cinema":                   (100, 1000),
    "mall":                     (500, 1000),
    "convenience":              (100, 500),
    "supermarket":              (100, 500),
    "cemetery":                 (100, 500),
    "religion":                 (100, 500),
    "market":                   (100, 500),
    "university":               (1000, 8000),
    "playground":               (10, 100),
    "pharmacy":                 (10, 50),
    "fuel":                     (10, 50),
    "beach":                    (500, 1000),
    "train_building":           (100, 500),
    "bank":                     (100, 500),
    "lawyer":                   (10, 50),
    "cafe":                     (10, 100),
    "hairdresser":              (10, 50),
    "restaurant":               (10, 100),
    "bar":                      (10, 100),
    "park":                     (100, 200),
    "government":               (10, 100),
    "hotel":                    (100, 500),
    "post":                     (10, 100),
    "police":                   (10, 100),
    "dog_park":                 (50, 100),
    "hostel":                   (10, 100),
    "bakery":                   (10, 100),
    "parking":                  (10, 100),
    "library":                  (50, 500)
}